stages:
  - androidbuild
  - androidtest 

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - ecabelin_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew build
  only:
    refs:
      - ecabelin_CICD
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - ecabelin_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew test
  only:
    refs:
      - ecabelin_CICD
    changes:
      - Frontend/**/*

